services:
    mongodb:
      image: mongo:latest
      environment:
        - MONGO_INITDB_ROOT_USERNAME=user
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGODB_CONNSTRING =
      restart: on-failure
      ports:
        - 27017:27017
      volumes:
        - ./mongodb:/data/db
   codecase:
     image: codecase:latest
     container_name: codecase
     build:
       .
     ports:
       - 8080:8080